version: '3'

services:

  db:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
      - PMA_ARBITRARY=1
      ports:
      - ${WP_PORT_PHPMA}:80
      volumes:
      - /sessions
      
  httpd:
    image: epflidevelop/os-wp-httpd
    volumes:
      - ./volumes/srv:/srv
    links:
      - db:db
    environment:
      - WP_ENV=${WP_ENV}
    ports:
      - "${WP_PORT_HTTP}:80"
      - "${WP_PORT_HTTPS}:443"

  mgmt:
    labels:
      ch.epfl.jahia2wp.mgmt.env: ${WP_ENV}
    image: epflidevelop/os-wp-mgmt
    env_file:
      - .env
    environment:
      - WP_ENV=${WP_ENV}
      - LOGGING_FILE=/srv/${WP_ENV}/logs/jahia2wp.log
    volumes:
      - ./volumes/srv:/srv
      - ./etc/.bash_history:/var/www/.bash_history
      - ./etc/.aliases:/srv/.aliases
      - ./etc/.bashrc:/srv/.bashrc
      - ./data:/srv/${WP_ENV}/jahia2wp/data
      - ./requirements:/srv/${WP_ENV}/jahia2wp/requirements
      - ./src:/srv/${WP_ENV}/jahia2wp/src
      - ./functional_tests:/srv/${WP_ENV}/jahia2wp/functional_tests
      - ./Makefile.mgmt:/srv/${WP_ENV}/jahia2wp/Makefile
      - .env:/srv/${WP_ENV}/jahia2wp/.env
    ports:
      - "${WP_PORT_SSHD}:22"

    
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - ./volumes/prometheus:/etc/prometheus
    ports:
        - "9090:9090"
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"
  
  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  cadvisor:
    image: google/cadvisor:latest
    ports:
        - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  # Documentation: http://elk-docker.readthedocs.io/#running-with-docker-compose
  elk:
    image: sebp/elk
    volumes:
      - ./volumes/logstash/conf/:/etc/logstash/conf.d/
    ports:
      - "5601:5601"

    # Documentation: https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.3
    volumes:
      - ./volumes/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./volumes/srv/${WP_ENV}/logs/:/var/wp-apache-log/
    links:
      - elk:elk